In [180]:
import pandas 
import openpyxl
import numpy as np
df = pandas.read_excel('test.xlsx')
df

Time  Mood  Reason  Action ID  Result
0      119     2      17         16      46
1       88     1       4          6      80
2       62     2      16          9      46
3       86     2       6          8      45
4      114     1       1          8      81
...    ...   ...     ...        ...     ...
9995    60     2      13          7      44
9996    16     1       8          9      77
9997    73     1      14         13      72
9998    33     2      10         19      48
9999    77     2      23         18      45

[10000 rows x 5 columns]

In [181]:
df =df[~df.isin([np.nan, np.inf, -np.inf]).any(1)]
df

Time  Mood  Reason  Action ID  Result
0      119     2      17         16      46
1       88     1       4          6      80
2       62     2      16          9      46
3       86     2       6          8      45
4      114     1       1          8      81
...    ...   ...     ...        ...     ...
9995    60     2      13          7      44
9996    16     1       8          9      77
9997    73     1      14         13      72
9998    33     2      10         19      48
9999    77     2      23         18      45

[10000 rows x 5 columns]

In [182]:
df =df[~df.isin([np.nan, np.inf, -np.inf]).any(1)]
df

Time  Mood  Reason  Action ID  Result
0      119     2      17         16      46
1       88     1       4          6      80
2       62     2      16          9      46
3       86     2       6          8      45
4      114     1       1          8      81
...    ...   ...     ...        ...     ...
9995    60     2      13          7      44
9996    16     1       8          9      77
9997    73     1      14         13      72
9998    33     2      10         19      48
9999    77     2      23         18      45

[10000 rows x 5 columns]

In [183]:
from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier(n_neighbors=3)
from sklearn.model_selection import train_test_split

In [184]:
y= df['Action ID']
y

0       16
1        6
2        9
3        8
4        8
        ..
9995     7
9996     9
9997    13
9998    19
9999    18
Name: Action ID, Length: 10000, dtype: int64

In [185]:
X = df.drop('Action ID', axis =1)
X

Time  Mood  Reason  Result
0      119     2      17      46
1       88     1       4      80
2       62     2      16      46
3       86     2       6      45
4      114     1       1      81
...    ...   ...     ...     ...
9995    60     2      13      44
9996    16     1       8      77
9997    73     1      14      72
9998    33     2      10      48
9999    77     2      23      45

[10000 rows x 4 columns]

In [186]:
X_train, X_test, y_train, y_test = train_test_split(
X, y, test_size=0.25, random_state=42)

In [187]:
y_test

6252    13
4684     3
1731     9
4742    14
4521    12
        ..
4862     6
7025     7
7647    19
7161    17
73      10
Name: Action ID, Length: 2500, dtype: int64

In [188]:
X_train

Time  Mood  Reason  Result
4901    19     1      23      70
4375    23     2      11      48
6698    79     2      23      43
9805    77     2       3      43
1101    90     1      21      78
...    ...   ...     ...     ...
5734    62     1       8      70
5191    88     1       1      76
5390    32     2      16      46
860     73     2      16      42
7270    38     2       1      47

[7500 rows x 4 columns]

In [189]:
y_train

4901     2
4375     2
6698    15
9805    16
1101     8
        ..
5734    14
5191    13
5390    15
860      5
7270    22
Name: Action ID, Length: 7500, dtype: int64

In [190]:
neigh.fit(X,y)


KNeighborsClassifier(n_neighbors=3)

In [191]:
neigh.score(X_train, y_train)

0.3814666666666667

Берем первую строку

In [192]:
for_test = df.iloc[[1]] 
for_test = for_test.drop('Action ID', axis =1)
for_test

Time  Mood  Reason  Result
1    88     1       4      80

Ниже предскзание категории для этой модели

In [193]:
neigh.predict(for_test)

array([5])

Экпортируем модель в файл

In [194]:
import pickle

In [195]:
filename = 'finalized_model.sav'
pickle.dump(neigh, open(filename, 'wb'))

Чтение модели из файла

In [196]:
loaded_model = pickle.load(open(filename, 'rb'))


Проверяем 

In [197]:
for_test = df.iloc[[111]] 
for_test = for_test.drop('Action ID', axis =1)
for_test

Time  Mood  Reason  Result
111    55     2      12      46

In [198]:
loaded_model.predict(for_test)

array([1])

Так как обычно весь обмен с беком от приложения происходит через json то надо понять его структуру

In [199]:
result = for_test.to_json(orient="records")

In [200]:
result

'[{"Time":55,"Mood":2,"Reason":12,"Result":46}]'

Создадим json с новыми данными

In [201]:
test2 = '[{"Time":111,"Mood":1,"Reason":7,"Result":90}]'

In [202]:
df_test = pandas.read_json(test2)
df_test

Time  Mood  Reason  Result
0   111     1       7      90

In [203]:
loaded_model.predict(df_test)

array([5])